version: "3.7"

services:
  multiplicacion:
    image: ghcr.io/misw-4301-desarrollo-apps-en-la-nube/s1-calculadora-numeros:vmultiplicacion-0.0.1
    ports:
      - 4000:4000

  suma:
    image: ghcr.io/misw-4301-desarrollo-apps-en-la-nube/s1-calculadora-numeros:vSuma-0.0.1
    ports:
      - 5000:4000
 