apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: calculadora-numeros
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: calculadora-numeros
  replicas: 5
